#+TITLE: Teaching duck-streams About Bytes

The [[http://github.com/bpsm/clojure-contrib/tree/ducks-byte][ducks-byte]] branch of *clojure-contrib* is my attempt to teach
duck-streams to be as convenient for byte streams as it now is for
textual streams.

* Features

- input-stream is like reader, except for bytes.

- output-stream is like writer, except for bytes.

- reader and writer now build on input-stream and output-stream
  where appropriate.

- I've taught input-stream to also try the CLASSPATH when given a
  String doesn't specify a File or a URL.

* Open Questions

*** teaching input-stream to try the CLASSPATH

Calls which previously would have failed (because no such file
existed) might now succeed because a resource of the same name
happens to exist on the CLASSPATH. Is this acceptable?

*** =*append-to-writer*= renamed

This might be a compatibility issue for clients that did not heed
the advice given in documentation to use append-writer or
append-spit instead of directly binding this var.

